### ISSUE TITLE
Reference to a non-existing FQCN in ES

### ISSUE THREAD

**Issue by ramondelafuente** [simple-es/doctrine-dbal-bridge#1]
https://github.com/simple-es/doctrine-dbal-bridge/blob/master/src/Event/Store/DBALEventStore.php#L14

This reads `Event\Resolver\ResolvesEventNames` but should be `Event\NameResolver\ResolvesEventNames` right?

**Comment by jaspernbrouwer** [comment]
Indeed, `SimpleES\EventSourcing\Event\NameResolver\ResolvesEventNames` is the correct one!

I had already fixed this, but hadn't pushed it yet. I've done so now! (264904d36a4341a9469ae5471072a21f1ceed3f3)
