### ISSUE TITLE
Perhaps add an example structure for the events table?

### ISSUE THREAD

**Issue by ramondelafuente** [simple-es/doctrine-dbal-bridge#2]
Currently, it needs to be reverse engineered fom the insert statement :-)

**Comment by jaspernbrouwer** [comment]
I agree, I'll add .sql files for SQLite, MySQL and PostgreSQL. Soon :)

PS: You can find a SQLite example in the integration test.

**Comment by jaspernbrouwer** [comment]
I've added the example .sql files, you can find them in `/docs`. (9ef83dbe74e41caf0c438359b15e2afa3980b92e)
